import Head from "next/head"
import Layout from "../components/Home/Layout"

export default function Home() {
  return (
    <>
      <Head>
        <title>The Met | Hari-devign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  )
}
